= FAQ - Espaces Aériens
Jean-Michel Bruel <jbruel@gmail.com>
v2026-08-27
include::definitions.adoc[]
:full:

== Introduction

Bienvenue dans cette FAQ (Foire Aux Questions) dédiée aux espaces aériens. 
Vous trouverez ici les réponses aux questions les plus fréquemment posées.

WARNING: Cette FAQ est en cours de développement. N'hésitez pas à nous faire part de vos questions.

NOTE: Les informations fournies ici sont à titre indicatif et ne remplacent pas les documents officiels (cf. <<Ressources>>).

== Questions fréquemment posées

include::casSurvol.adoc[leveloffset=+2]
include::airprox.adoc[leveloffset=+2]
include::aerodromes.adoc[leveloffset=+2]
include::notam.adoc[leveloffset=+2]
include::activation.adoc[leveloffset=+2]
include::delais.adoc[leveloffset=+2]
include::semaphore.adoc[leveloffset=+2]
include::referent-mission.adoc[leveloffset=+2]
include::referents.adoc[leveloffset=+2]

== Questions Générales

=== Qu'est-ce qu'un espace aérien ?

Un espace aérien est une région de l'atmosphère définie par des limites géographiques et verticales, soumise à des règles de circulation aérienne spécifiques.

WARNING: To be continued...

=== Quels sont les différents types d'espaces aériens ?

Les espaces aériens se classent en plusieurs catégories selon leur utilisation et les règles applicables.

WARNING: To be continued...

== Réglementation

=== Qui réglemente les espaces aériens ?

Les autorités aéronautiques nationales et les organismes internationaux comme l'OACI (Organisation de l'Aviation Civile Internationale) définissent les règles.

WARNING: To be continued...

== Accès et Utilisation

WARNING: To be continued...

=== Comment accéder à un espace aérien contrôlé ?

L'accès à un espace aérien contrôlé nécessite une autorisation préalable et le respect des procédures établies.

WARNING: To be continued...


== Exemples

include::tuchan.adoc[leveloffset=+2]
include::luchon.adoc[leveloffset=+2]
include::peyresourde.adoc[leveloffset=+2]
include::zone-centre.adoc[leveloffset=+2]


== Contact

Pour toute question supplémentaire, n'hésitez pas à mailto:{referentemail}[nous contacter].

[appendix]

[[Resources]]
== Ressources

=== Documents officiels (autorités aéronautiques, fédérations, ...)

- https://www.aviation-civile.gouv.fr[🇫🇷 DGAC - Direction Générale de l'Aviation Civile]
- https://www.easa.europa.eu[🇬🇧 EASA - Agence Européenne de la Sécurité Aérienne]
- https://www.icao.int/fr[🇫🇷 OACI - Organisation de l'Aviation Civile Internationale]
- Liste des référents espaces aériens FFVL https://federation.ffvl.fr/sites/ffvl.fr/files/Referents_EA_FFVL_par_CCRAGALS-DSAC_Ligue_et_CDVL-2026_0.pdf[🇫🇷 PDF]

.Conversions
[TIP]
=====
Les hauteurs ou les altitudes sont généralement exprimées en pieds (`ft`) dans le milieu de l'aviation.
Pour convertir des pieds en mètres, utilisez la formule suivante :
1 pied = 0,3048 mètre

Exemple : 1000 ft = 1000 x 0,3048 = 304,8 m.

Pour faire simple on multiplie par 3 et on enlève un zéro (on divise par 10) pour obtenir une valeur approchée en mètres.
=====

=== Outils et applications

- https://flysafe.aero/[🇫🇷 Flysafe]
[appendix]

include::acronymes.adoc[leveloffset=+1]
